# Generated by Django 2.0.6 on 2018-06-07 19:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    replaces = [('authorities', '0001_initial'), ('authorities', '0002_auto_20180607_2251')]

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Authority',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Όνομα')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AuthorityKind',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Όνομα')),
            ],
            options={
                'verbose_name': 'Authority Kind',
                'verbose_name_plural': 'Authority Kinds',
            },
        ),
        migrations.AddField(
            model_name='authority',
            name='kind',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='authorities.AuthorityKind', verbose_name='Kind'),
        ),
        migrations.AddField(
            model_name='authority',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='authorities.Authority', verbose_name='Parent'),
        ),
        migrations.AddField(
            model_name='authority',
            name='users',
            field=models.ManyToManyField(related_name='authority_user', to=settings.AUTH_USER_MODEL, verbose_name='Authority users'),
        ),
        migrations.AlterModelOptions(
            name='authority',
            options={'verbose_name': 'Authority', 'verbose_name_plural': 'Authorities'},
        ),
        migrations.AlterField(
            model_name='authority',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='authorities.Authority', verbose_name='Parent'),
        ),
        migrations.AlterField(
            model_name='authority',
            name='users',
            field=models.ManyToManyField(blank=True, related_name='authorities', to=settings.AUTH_USER_MODEL, verbose_name='Authority users'),
        ),
    ]
